# Server port
server.port=8080
spring.applicartion.name=TaskManagementTool1

# H2 Database
spring.datasource.url=jdbc:mysql://localhost:3306/taskmanagemnt_tool1

spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.springframework=INFO

# Cloudinary (replace with your credentials)
cloudinary.cloud_name=YOUR_CLOUD_NAME
cloudinary.api_key=YOUR_API_KEY
cloudinary.api_secret=YOUR_API_SECRET
